GET http://localhost:4000/ping

###
GET http://localhost:4000/eventos/eventos

###
GET http://localhost:4000/eventos/semana-formacao-dev

###

GET http://localhost:4000/eventos/2fbb3647-2492-4901-95ad-70b9d49d63d4

###
GET http://localhost:4000/eventos/validar/evento-fullstack/2fbb3647-2492-4901-95ad-70b9d49d63d4

###
POST http://localhost:4000/eventos/acessar
Content-Type: application/json

  {
    "id": "d0f03cc8-2df5-42b7-8ad9-7bb3a122756d",
    "senha": "estrela2024"
  }

###
POST http://localhost:4000/eventos/casamento-alberto-marina/convidado
Content-Type: application/json

{
    "id": "b1a60ac7-3904-420d-862a-18d14461833",
    "nome": "Viviane Silva",
    "email": "vivianesilva@outlook.com",
    "confirmado": true,
    "possuiAcompanhantes": true,
    "qtdeAcompanhantes": 10
}
###
POST http://localhost:4000/eventos
Content-Type: application/json

{
    "alias": "Fullstack-Java",
    "nome": "Evento Semana Formação.Java",
    "data": "2025-12-31T23:00",
    "local": "São Paulo",
    "descricao": "Evento de tecnologia",
    "senha": "frameworks2025",
    "imagem": "https://www.formacao.dev/assets/img/formacao-dev.png",
    "imagemBackground": "https://www.formacao.dev/assets/img/formacao-dev-background.png",
    "publicoEsperado": 5000,
    "convidados": [
        {

            "nome": "Viviane Silva",
            "email": "vivianeaguiar@outlook.com",
            "confirmado": true,
            "possuiAcompanhantes": true,
            "qtdeAcompanhantes": 10
        }
    ]
}